version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "MyLambdaFunction"
        Alias: "prod"
        CurrentVersion: "1" # Placeholder for the current version
        TargetVersion: "2"  # Placeholder for the new version
